# Generated by Django 5.0.1 on 2024-01-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connection',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
