# Generated by Django 5.0.1 on 2024-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_person_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
